"""Portable export formats for recruiter-facing skill-gap reports."""

from __future__ import annotations

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from .skill_gap import SkillGapReport


def build_skill_gap_pdf(report: SkillGapReport) -> bytes:
    """Build a compact, styled PDF report suitable for download."""
    output = BytesIO()
    document = SimpleDocTemplate(output, pagesize=A4, rightMargin=42, leftMargin=42, topMargin=42, bottomMargin=42)
    styles = getSampleStyleSheet()
    title = ParagraphStyle("ReportTitle", parent=styles["Title"], textColor=colors.HexColor("#17324D"), fontSize=22, leading=27)
    subtitle = ParagraphStyle("Subtitle", parent=styles["Normal"], textColor=colors.HexColor("#64748B"), fontSize=10, leading=15)
    section = ParagraphStyle("Section", parent=styles["Heading2"], textColor=colors.HexColor("#274C77"), fontSize=13, leading=17, spaceBefore=14)
    body = ParagraphStyle("Body", parent=styles["BodyText"], textColor=colors.HexColor("#334155"), fontSize=10, leading=15)
    score = report.hiring_score
    story = [
        Paragraph("Skill-Gap Report", title),
        Paragraph(f"Candidate: {report.candidate_name}<br/>Role: {report.job_title}", subtitle),
        Spacer(1, 16),
    ]
    score_table = Table([["Hiring score", "Recommendation", "Matched skills", "Skill gaps"], [f"{score.total}/100", score.recommendation, str(len(report.matched_skills)), str(len(report.missing_skills))]], colWidths=[1.25 * inch, 2.0 * inch, 1.35 * inch, 1.25 * inch])
    score_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EAF3FD")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#1D4E89")),
        ("TEXTCOLOR", (0, 1), (-1, 1), colors.HexColor("#17324D")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D8E2EE")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#D8E2EE")),
        ("TOPPADDING", (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 9),
    ]))
    story.extend([score_table, Paragraph("Assessment summary", section), Paragraph(report.summary, body)])
    for heading, items in [("Matched skills", report.matched_skills), ("Skill gaps", report.missing_skills)]:
        text = ", ".join(items) if items else "None"
        story.extend([Paragraph(heading, section), Paragraph(text, body)])
    story.extend([Spacer(1, 20), Paragraph("Generated by RecruitAI Copilot", subtitle)])
    document.build(story)
    return output.getvalue()
